# Generated by Django 5.1.3 on 2024-11-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livros_streaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
